version: 0.2

env:
    variables:
      build_message: "mais um teste"
    exported-variables:
      - build_message

phases:
  pre_build:
    commands:
      - sudo apt update
      - sudo apt install awscli
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform apply -var-file="dev-app.tfvars" --auto-approve
  
  post_build:
    commands:
     - aws lambda update-function-configuration --function-name PSTest --environment "Variables={mensagem=teste 1234}"
     - aws --version
