version: 0.2
phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform apply -var-file="dev-app.tfvars" --auto-approve
  
  post_build:
    env:
      variables:
        - build_message: "mais um teste"
      exported-variables:
        - build_message