version: 0.2

env:
    variables:
      build_message: "mais um teste"
    exported-variables:
      - build_message

phases:
  pre_build:
    commands:
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
      - cd $CODEBUILD_SRC_DIR
      - terraform --version
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform apply -var-file="dev-app.tfvars" --auto-approve
  
  post_build:
    commands:
     - aws lambda update-function-configuration --function-name PSTest --environment "Variables={mensagem=teste 1234}"
     - aws --version
