version: 0.2

#env:
#    variables:
#      RUNNERUSER: $runnerUser
#      RUNNERDEVICE: $runnerDevice
    

phases:
  pre_build:
    commands:
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      - cd $CODEBUILD_SRC_DIR
      - terraform --version
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform apply -var-file="dev-app.tfvars" --auto-approve
  
  post_build:
    commands:
     - echo ${RUNNER_USER}
     - echo ${runner_User}
     - echo ${RUNNER_DEVICE}
     - aws lambda update-function-configuration --function-name PSTest --environment "Variables={runnerUser=$runner_User,runnerDevice=$runner_Device}"
     
